version: '2.1'

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: vespyr
      POSTGRES_PASSWORD: password
