apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-bot
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-not
    spec:
      nodeSelector:
          cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: {{ .Chart.Name }}-bot
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["bot"]
        env:
{{ include "environment" . | indent 10 }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
