// Code generated by mockery v1.0.0
package vespyr

import mock "github.com/stretchr/testify/mock"

// MockIndicator is an autogenerated mock type for the Indicator type
type MockIndicator struct {
	mock.Mock
}

// AddCandlestick provides a mock function with given fields: c
func (_m *MockIndicator) AddCandlestick(c *CandlestickModel) error {
	ret := _m.Called(c)

	var r0 error
	if rf, ok := ret.Get(0).(func(*CandlestickModel) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Name provides a mock function with given fields:
func (_m *MockIndicator) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Value provides a mock function with given fields:
func (_m *MockIndicator) Value() (*IndicatorValue, error) {
	ret := _m.Called()

	var r0 *IndicatorValue
	if rf, ok := ret.Get(0).(func() *IndicatorValue); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IndicatorValue)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
