# Default values for vespyr-realtime-importer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
secretKey: vespyr-staging
image:
  repository: ""
  tag: master
  pullPolicy: Always
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
app:
  env: "staging"
  slackTradesChannel: "#trades-staging"
  slackDataChannel: "#data-staging"
  useFakeExchange: "true"
